### ISSUE TITLE
Auto stop listening after a few seconds

### ISSUE THREAD

**Issue by derweba** [evancohen/smart-mirror#477]
I don't know if this feature is implemented yet,

but if i say the Keyword, the SmartMirror never stops listening.

So basically i say the KeyWord and then the white bar is appearing. Then the voice recognition is sometimes working sometimes it isn't working. It would be a good feature if the voice recognition stops listening, especially because of the 60min of free speech recognition time from the Google Cloud Speech (or amn't I right informed?) and the sometimes self starting voice recognition because of a false KeyWord detection.

And by the way, I have extended the code so i can turn the gpio pins of my Raspberry on and of. Is there any need to publish this, and if, how should i publish it? (Sry, i'm quiet new to GitHub...)

**Comment by justbill2020** [comment]
what microphone are you using... its possible its not picking up your voice properly for google to work... however you shouldn't have it on all the time... its not normal operation.

**Comment by derweba** [comment]
I am using a "Kinobo Kanji USB 2.0 Mikrofon"... this is a recommended microphone from other voice recognition projects.
But how can i stop the listening process? Or is there any timeout until google stops listening?

**Comment by justbill2020** [comment]
it stops automatically when it stops detecting noise... if the light at the bottom is staying on the mic is constantly picking up noise. I have that microphone it is cheap but works for crap. The smart-mirror is both more sensitive than other project and more accurate voice detection. I would recommend getting a PS3 Eye... it has a 4 Microphone array and works great!

**Comment by derweba** [comment]
Ok... i will try the other microphone and will repeply if it solved the problem.

And to my question I mentioned above: "I have extended the code so i can turn the gpio pins of my Raspberry on and of. Is there any need to publish this, and if, how should i publish it? (Sry, i'm quiet new to GitHub...)"

**Comment by justbill2020** [comment]
Well... you might not... will it contribute to the community and overall project? if its just a one off for your purposes extention you might not need to send it to the master repo... but then you have to maintain your code inline with the master...

head over to [gitterim](https://gitter.im/evancohen/smart-mirror) and we can discuss further... i'll help you out there...

**Comment by taran27** [comment]
yeah this suggestion is gr8 it needs to stop listening after few seconds...!

**Comment by evancohen** [comment]
Just looked at this. It's a problem both in the mirror and in sonus. If you don't say anything after the mirror detects "smart mirror" we never detect a `final-results` event (which we use to determine when the mirror stops listening).

We'll have to see if there's another event that we can add (like "no-results")  that we can use for this as well.

**Comment by mkings007** [comment]
which microphone do i use for smart mirror

**Comment by derweba** [comment]
Switching to the "PS3 Eye" microphone didn't solved the issue, but it made the recognition better.

**Comment by evancohen** [comment]
This is a known bug in sonus. When there is an empty transcript we never emit `final-results` so we don't know that the mirror is done listening.

There is now an open PR to fix this: evancohen/sonus#27
This should be fixed shortly :)

**Comment by evancohen** [comment]
Fix available with remote work.

**Comment by justbill2020** [comment]
@derweba is this now resolved? 

It should have been resolved in PR #500 version 0.0.8 update to `master`... also resolved in `dev`

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
Verified that this is fixed in master with the latest version of Sonus

**Comment by justbill2020** [comment]
still not fixed @evancohen its happening on my pi and on @justkrisp's pi... it just never goes away no errors just stays there

**Comment by justbill2020** [comment]
@evancohen this was caused to issues with google api... should still have a time out for listening though on the UI...

**Comment by evancohen** [comment]
Porque? I think a persistent white bar is pretty indicative of something being wrong:
- Billing not enabled
- Google speech down
- etc

And we don't even have to write any code!
