### ISSUE TITLE
ERROR e:2698

### ISSUE THREAD

**Issue by XPMCoding** [evancohen/smart-mirror#493]
After about two minutes the mic stops working and I get a ERROR e:2698) UnhandledPromisRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: stdout maxBuffer exceeded

**Comment by evancohen** [comment]
This should be fixed in the most recent version (latest in `master`). See #462.

 Can you update and try again?

**Comment by XPMCoding** [comment]
I have, I run git pull and I still get the same issue but sometimes its different error numbers like i just got ERROR: 5329 but it says the same stuff after it

**Comment by evancohen** [comment]
My guess is that you haven't updated your dependencies. The error is coming from an old version of the audio recording library that we use.

**Comment by XPMCoding** [comment]
how do I update the dependencies?

**Comment by XPMCoding** [comment]
nvm I figured out how

**Comment by evancohen** [comment]
Hopefully this fixed, if you're still having issues feel free to re-open.
